### ISSUE TITLE
MountMuzzle Making FFXI stop responding

### ISSUE THREAD

**Issue by Meenme** [Ap0gee/MountMuzzle#3]
Hi, I am not sure if you have seen this before but I have MM make FFXI stop responding when shutting down or logging out.  Using Windows 10, windower, dgvodoo.  a bunch of video mods.   I can get you more information if you need, or if you have any idea as to how to fix that info would be great.  Miss having zone music and would like to use it again

**Comment by Sjshovan** [comment]
Hi Meenme, sorry you are encountering this issue and thank you for reporting this! Can you please describe  how you were able to verify that MountMuzzle was indeed causing the problem? Can you tell me which version of MountMuzzle you are currently using? If you are unsure you can look in the readme within the MountMuzzle folder or in game, with MountMuzzle loaded, you can type `//mm a` or you can also click the `about` link on MountMuzzle within Windower addon selection. This will take you to the Readme. Have you used a previous version of MountMuzzle and if so, was this problem present then as well?  What methods are you using to log out and shut down? Does this issue occur regardless of the method? Do you log out and or shut down in the same place each time? Did you try re-installing MountMuzzle?
Here is an invite to the official Windower support Discord channel: https://discord.gg/NWrVQh
I am also there if you prefer that method of chat.

**Comment by Meenme** [comment]
I will check the Version and get back to you in the morning (I am PST).  I know its MM because I reinstalled all my windower after I started getting this issue about a month ago.  Thinking I had a older version of windowers I did a full install of it into another location and fresh installed all my plugins, used it without issues for about 2 weeks until last night I realized I hadn't reinstalled MM as soon as I did I got the issue of the not responding on logout/quitting.  It will stop responding if I select cancel on the initial FFXI load agreement page and anyplace I logout, or shutdown from.  Pretty much from the moment that MM loads will cause the issue.  I have since removed MM and haven't had the issue again.  I will get you the version of MM and windowers also.

**Comment by Meenme** [comment]
MM V0.9.4 Windower 4.3.6774.39167.  I checked both versions of MM I had used and it was the same version on both.

**Comment by Sjshovan** [comment]
I believe I have found what and where the problem is. I will get this fixed asap. Keep an eye out for the update, it may take some time to get through Windower's dev team to be accepted and merged. If you would like to be notified when this fix goes live I tweet my updates at `@sjshovan`. Thanks again!

**Comment by Meenme** [comment]
Cool, appreciate the work you do and thanks again.
